export const siteCopy = {
  ru: {
    catalog: "Каталог", match: "Подбор", venues: "Для менеджера",
    assistant: "Ассистент", manager: "Для менеджера", cta: "Подобрать с AI",
    brandAria: "ToiMatch — на главную",
    navigation: "Основная навигация", language: "Язык интерфейса", skip: "Перейти к содержимому",
    menuOpen: "Открыть меню", menuClose: "Закрыть меню", menu: "Меню",
    tagline: "Подрядчики для тоя, свадьбы и корпоратива — с объяснением каждого выбора.",
    data: "66 анонимизированных профилей подрядчиков · HackAlem AI 2026",
    photo: "Фото подрядчиков — ИИ-иллюстрации. Выбор объясняем фактами из каталога.",
    rights: "© 2026 ToiMatch",
    notFoundCode: "Ошибка 404",
    notFound: "Страница не найдена", notFoundText: "Возможно, ссылка устарела. Найдите подрядчика в каталоге или начните подбор с AI.",
    notFoundMatch: "Подобрать с AI",
    mascotAlt: "Нурлан, консьерж ToiMatch, разводит руками",
  },
  kk: {
    catalog: "Каталог", match: "Іріктеу", venues: "Менеджерге",
    assistant: "Көмекші", manager: "Менеджерге", cta: "AI арқылы таңдау",
    brandAria: "ToiMatch — басты бет",
    navigation: "Негізгі навигация", language: "Интерфейс тілі", skip: "Мазмұнға өту",
    menuOpen: "Мәзірді ашу", menuClose: "Мәзірді жабу", menu: "Мәзір",
    tagline: "Той, үйлену тойы және корпоратив үшін мердігерлер — әр таңдау түсіндіріледі.",
    data: "Мердігерлердің 66 анонимдендірілген профилі · HackAlem AI 2026",
    photo: "Мердігер фотолары — ЖИ иллюстрациялары. Әр таңдауды каталог деректерімен түсіндіреміз.",
    rights: "© 2026 ToiMatch",
    notFoundCode: "404 қатесі",
    notFound: "Бет табылмады", notFoundText: "Сілтеме ескірген болуы мүмкін. Каталогтан мердігер табыңыз немесе AI арқылы іріктеуді бастаңыз.",
    notFoundMatch: "AI арқылы таңдау",
    mascotAlt: "ToiMatch консьержі Нұрлан қолын жаяды",
  },
  en: {
    catalog: "Catalog", match: "Match", venues: "For managers",
    assistant: "Assistant", manager: "For managers", cta: "Match with AI",
    brandAria: "ToiMatch — home",
    navigation: "Main navigation", language: "Interface language", skip: "Skip to content",
    menuOpen: "Open menu", menuClose: "Close menu", menu: "Menu",
    tagline: "Contractors for toi, weddings and corporate events — every choice explained.",
    data: "66 anonymized contractor profiles · HackAlem AI 2026",
    photo: "Contractor photos are AI illustrations. Every choice is explained with catalog facts.",
    rights: "© 2026 ToiMatch",
    notFoundCode: "Error 404",
    notFound: "Page not found", notFoundText: "This link may be out of date. Find a contractor in the catalog or start matching with AI.",
    notFoundMatch: "Match with AI",
    mascotAlt: "Nurlan, the ToiMatch concierge, shrugging",
  },
};

export type SiteCopy = (typeof siteCopy)["ru"];
